### ISSUE TITLE
How do I exclude an individual file?

### ISSUE THREAD

**Issue by davidwilde** [alex-seville/grunt-blanket#7]
I notice in your README you say that it is possible to exclude individual files in the pattern but I'm being a bit thick and can't seem to do it. Any chance of an example?

I'm trying this:

```
    blanket:
        options: {}
        files:
            expand: false
            src: ['!dev/app/app.js','/dev/app/']
            dest: './coverage/app/'
```
